DEFAULT_SERVER_PORT = 3001
DEFAULT_SEED = 1234
DEFAULT_TEST_HOLDOUT_PROP = 0.2
DEFAULT_TRAIN_SPLIT_PROP = 0.85
DEFAULT_USER_INTERACTIONS_THRESHOLD = 5
DEFAULT_ITEM_INTERACTIONS_THRESHOLD = 0
DEFAULT_INTERACTION_VALUE_THRESHOLD = 0
