CURRENT_VERSION = "0.2.6"

DEFAULT_CHECKPOINTS_DIR = ".repsys_checkpoints"
DEFAULT_SERVER_PORT = 3001
DEFAULT_SEED = 1234

DEFAULT_TEST_HOLDOUT_PROP = 0.2
DEFAULT_TRAIN_SPLIT_PROP = 0.85
DEFAULT_MIN_USER_INTERACTS = 0
DEFAULT_MIN_ITEM_INTERACTS = 0

DEFAULT_PRECISION_RECALL_K = [20, 50]
DEFAULT_NDCG_K = [100]
DEFAULT_COVERAGE_K = [20]
DEFAULT_DIVERSITY_K = [20]
DEFAULT_NOVELTY_K = [20]
DEFAULT_PERCENTAGE_LT_K = [20]
DEFAULT_COVERAGE_LT_K = [20]

DEFAULT_TSNE_PERPLEXITY = 30
DEFAULT_UMAP_MIN_DIST = 0.1
DEFAULT_PYMDE_NEIGHBORS = 15
DEFAULT_UMAP_NEIGHBORS = 15
